author: GARPIX
output: docs
theme: jony
swift_build_tool: xcodebuild
build_tool_arguments:
  - -scheme
  - GXUtilz
  - -sdk
  - iphoneos
  - -destination,platform=iOS Simulator,OS=latest,name=iPhone 11 Pro