name: PublishDocumentation
on: 
  release:
    types: [published]
jobs:
  deploy_docs:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish Jazzy Docs
      uses: sersoft-gmbh/swifty-docs-action@v1
      with:
        xcodebuild-scheme: GXUtilz
        xcodebuild-sdk: iphoneos
        xcodebuild-destination: 'platform=iOS Simulator,OS=latest,name=iPhone 11 Pro'
